name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}
      GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar o Poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Executar testes
        run: echo "testes executados com sucesso. (Isso é apenas um teste XD)"